### ISSUE TITLE
Was Working Fine But Suddenly Stop Sending New Releases

### ISSUE THREAD

**Issue by itsmechinmoy** [kaorlol/obtainium-artifact-downloader#2]
![image](https://github.com/kaorlol/obtainium-artifact-downloader/assets/167056923/9183c42c-8186-4792-b6ef-05babc8ccf36)
a new update came 3 hrs ago

**Comment by itsmechinmoy** [comment]
same with my other repos too
it shows that a commit was added but no release
![image](https://github.com/kaorlol/obtainium-artifact-downloader/assets/167056923/6e792837-8588-4a93-9988-3b22fc0f5d03)

**Comment by itsmechinmoy** [comment]
but i checked ur dantotsu updater its working fine T_T

**Comment by itsmechinmoy** [comment]
![image](https://github.com/kaorlol/obtainium-artifact-downloader/assets/167056923/02036368-c643-4203-93bf-38d0c4d8fe24)
its showing updated for each of them but no new release 
if i remember correctly something like this happened to u b4r

**Comment by kaorlol** [comment]
i use this same repo for my dantotsu updater so i have no clue why it stopped working for you

**Comment by kaorlol** [comment]
nvm, i have found the issue. Fixing.

**Comment by kaorlol** [comment]
I dont think templates update all repos that use it so just change this line:

data.UpdateInfo(data.Info{ElapsedTime: time.Since(prevTime).Seconds()})

to this:

data.UpdateInfo(data.Info{ElapsedTime: time.Since(prevTime).Seconds(), Status: "success"})

in https://github.com/itsmechinmoy/dantotsu-updater/blob/master/src/main.go
